require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5.8
  TargetRailsVersion: 5.2.5
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

# 日本語コメントの許可
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメントないclass module
Style/Documentation:
  Enabled: false

# 数字の _ による区切り
Style/NumericLiterals:
  Enabled: false

# gemのインストール順
Bundler/OrderedGems:
  Enabled: false

# classの記述形式をネスト、コンパクトで指定しない
ClassAndModuleChildren:
  Enabled: false

# let subjectの個数制限
Metrics/BlockLength:
  Exclude:
    - spec/**/*

#specファイル先頭のdescribeが定数であること
RSpec/DescribeClass:
  Enabled: false

#contextに使用される語が規定のものであること
RSpec/ContextWording:
  Enabled: false

#テスト条件のネスト制限
RSpec/NestedGroups:
  Max: 4

#expectの個数制限
RSpec/MultipleExpectations:
  Max: 4

#行数の長さ制限
RSpec/ExampleLength:
  Max: 7

#let subjectの個数制限
RSpec/MultipleMemoizedHelpers:
  Max: 6