version: '3'
services:
  db:
    container_name: trainu_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    container_name: trainu
    volumes:
      - .:/trainu:cached
      - /trainu/vendor
      - /trainu/tmp/chache
      - /trainu/tmp/db
      - /trainu/tmp/pids
      - /trainu/tmp/sockets
      - /trainu/tmp/storage
      - /trainu/log
      - /trainu/.git
    ports:
      - "3000:3000"
    environment:
      - "SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub"
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
