version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.8
        environment:
          POSTGRES_USER: postgres
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: postgres
          #パスワード入力省略でサーバーログイン
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: trainu_test
    working_directory: ~/trainu
    steps:
      - run:
          name: Chrome Driver Install
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install -y unzip
            wget -N http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo chown root:root ~/chromedriver
            sudo chmod 755 ~/chromedriver
            sudo mv ~/chromedriver /usr/bin/chromedriver
            sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -'
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update && sudo apt-get install -y google-chrome-stable
          background: true
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      # bundle install
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 1.16.6
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # bundle キャッシュ保存
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: DB Wait for Start
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      - run: mv ./config/database.yml.ci ./config/database.yml

      - run:
          name: DBsetup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load

      # rubocop実行
      - run:
          name: Rubocop
          command: bundle exec rubocop

      # rspec実行
      - run:
          name: Run rspec
          command: bundle exec rspec