default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  port: 5432
  pool: 5

development:
  <<: *default
  database: trainu_development

test:
  <<: *default
  database: trainu_test

production:
  url: <%= ENV['DATABASE_URL'] %>
